// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/recovery": {
    params: {};
  };
  "/reset-password/:token": {
    params: {
      "token": string;
    };
  };
  "/logout": {
    params: {};
  };
  "/posts/new": {
    params: {};
  };
  "/posts/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/posts/:id": {
    params: {
      "id": string;
    };
  };
  "/about": {
    params: {};
  };
  "/.well-known/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/auth/login" | "/auth/register" | "/auth/recovery" | "/reset-password/:token" | "/logout" | "/posts/new" | "/posts/:id/edit" | "/posts/:id" | "/about" | "/.well-known/*" | "/*";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth" | "/auth/login" | "/auth/register" | "/auth/recovery";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.recovery.tsx": {
    id: "routes/auth.recovery";
    page: "/auth/recovery";
  };
  "routes/reset-password.$token.tsx": {
    id: "routes/reset-password.$token";
    page: "/reset-password/:token";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/_app.tsx": {
    id: "routes/_app";
    page: "/" | "/posts/new" | "/posts/:id/edit" | "/posts/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/posts.new.tsx": {
    id: "routes/posts.new";
    page: "/posts/new";
  };
  "routes/posts.$id.edit.tsx": {
    id: "routes/posts.$id.edit";
    page: "/posts/:id/edit";
  };
  "routes/posts.$id.tsx": {
    id: "routes/posts.$id";
    page: "/posts/:id";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/well-known.tsx": {
    id: "routes/well-known";
    page: "/.well-known/*";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "routes/auth": typeof import("./src/app/routes/auth.tsx");
  "routes/auth.login": typeof import("./src/app/routes/auth.login.tsx");
  "routes/auth.register": typeof import("./src/app/routes/auth.register.tsx");
  "routes/auth.recovery": typeof import("./src/app/routes/auth.recovery.tsx");
  "routes/reset-password.$token": typeof import("./src/app/routes/reset-password.$token.tsx");
  "routes/logout": typeof import("./src/app/routes/logout.tsx");
  "routes/_app": typeof import("./src/app/routes/_app.tsx");
  "routes/home": typeof import("./src/app/routes/home.tsx");
  "routes/posts.new": typeof import("./src/app/routes/posts.new.tsx");
  "routes/posts.$id.edit": typeof import("./src/app/routes/posts.$id.edit.tsx");
  "routes/posts.$id": typeof import("./src/app/routes/posts.$id.tsx");
  "routes/about": typeof import("./src/app/routes/about.tsx");
  "routes/well-known": typeof import("./src/app/routes/well-known.tsx");
  "routes/$": typeof import("./src/app/routes/$.tsx");
};