// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/recovery": {
    params: {};
  };
  "/posts": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/.well-known/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/auth/login" | "/auth/register" | "/auth/recovery" | "/posts" | "/about" | "/.well-known/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth" | "/auth/login" | "/auth/register" | "/auth/recovery";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.recovery.tsx": {
    id: "routes/auth.recovery";
    page: "/auth/recovery";
  };
  "routes/posts.tsx": {
    id: "routes/posts";
    page: "/posts";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/well-known.tsx": {
    id: "routes/well-known";
    page: "/.well-known/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "routes/home": typeof import("./src/app/routes/home.tsx");
  "routes/auth": typeof import("./src/app/routes/auth.tsx");
  "routes/auth.login": typeof import("./src/app/routes/auth.login.tsx");
  "routes/auth.register": typeof import("./src/app/routes/auth.register.tsx");
  "routes/auth.recovery": typeof import("./src/app/routes/auth.recovery.tsx");
  "routes/posts": typeof import("./src/app/routes/posts.tsx");
  "routes/about": typeof import("./src/app/routes/about.tsx");
  "routes/well-known": typeof import("./src/app/routes/well-known.tsx");
};